server:
  port: 8887
spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.19.0.19:3306/testquery?useUnicode=true&characterEncoding=UTF-8&useSSL=false
  jpa:
    hibernate:
     # ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.springframework.web: trace
    com.example.demo.service: info
